[features]
seeds = true
skip-lint = false

[programs.devnet]
greylocker = "GREY1ockrXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
greylocker_vault = "GREY1vauLtXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
greylocker_zkp = "GREY1zkpXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

[programs.mainnet]
greylocker = "GREY1ockrXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
greylocker_vault = "GREY1vauLtXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
greylocker_zkp = "GREY1zkpXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
build = "anchor build"
deploy = "anchor deploy --provider.cluster devnet"
